# encoding: utf-8
require File.expand_path(File.dirname(__FILE__)) + '/../test_helper'

# This file is generated by the Ruby Holiday gem.
#
# Definitions loaded: data/cn.yaml
class CnDefinitionTests < Test::Unit::TestCase  # :nodoc:

  def test_cn
{Date.civil(2016,1,1) => "New Year's Day",
 Date.civil(2016,2,8) => "1. Spring Festival",
 Date.civil(2016,2,9) => "2. Spring Festival",
 Date.civil(2016,2,10) => "3. Spring Festival",
 Date.civil(2016,2,11) => "4. Spring Festival",
 Date.civil(2016,2,12) => "5. Spring Festival",
 Date.civil(2016,4,4) => "Qingming Festival",
 Date.civil(2016,5,2) => "Labor Day",
 Date.civil(2016,6,9) => "1. Dragon Boat Festival",
 Date.civil(2016,6,10) => "2. Dragon Boat Festival",
 Date.civil(2016,9,15) => "1. Mid-Autumn Festival",
 Date.civil(2016,9,16) => "2. Mid-Autumn Festival",
 Date.civil(2016,10,3) => "1. National Day",
 Date.civil(2016,10,4) => "2. National Day",
 Date.civil(2016,10,5) => "3. National Day",
 Date.civil(2016,10,6) => "4. National Day",
 Date.civil(2016,10,7) => "5. National Day",}.each do |date, name|
  assert_equal name, (Holidays.on(date, :cn, :informal)[0] || {})[:name]
end

  end
end
