# encoding: utf-8
module Holidays
  # This file is generated by the Ruby Holidays gem.
  #
  # Definitions loaded: data/us_banking.yaml
  #
  # To use the definitions in this file, load it right after you load the 
  # Holiday gem:
  #
  #   require 'holidays'
  #   require 'holidays/us_banking'
  #
  # All the definitions are available at https://github.com/alexdunae/holidays
  module US_Banking # :nodoc:
    def self.defined_regions
      [:us_banking]
    end

    def self.holidays_by_month
      {
              1 => [{:mday => 1, :observed => lambda { |date| Holidays.to_monday_if_sunday(date) }, :observed_id => "to_monday_if_sunday", :name => "New Year's Day", :regions => [:us_banking]},
            {:wday => 1, :week => 3, :name => "Martin Luther King, Jr. Day", :regions => [:us_banking]}],
      2 => [{:wday => 1, :week => 3, :name => "Presidents' Day", :regions => [:us_banking]}],
      5 => [{:wday => 1, :week => -1, :name => "Memorial Day", :regions => [:us_banking]}],
      7 => [{:mday => 4, :observed => lambda { |date| Holidays.to_monday_if_sunday(date) }, :observed_id => "to_monday_if_sunday", :name => "Independence Day", :regions => [:us_banking]}],
      9 => [{:wday => 1, :week => 1, :name => "Labor Day", :regions => [:us_banking]}],
      10 => [{:wday => 1, :week => 2, :name => "Columbus Day", :regions => [:us_banking]}],
      11 => [{:mday => 11, :observed => lambda { |date| Holidays.to_monday_if_sunday(date) }, :observed_id => "to_monday_if_sunday", :name => "Veterans Day", :regions => [:us_banking]},
            {:wday => 4, :week => 4, :name => "Thanksgiving", :regions => [:us_banking]}],
      12 => [{:mday => 25, :observed => lambda { |date| Holidays.to_monday_if_sunday(date) }, :observed_id => "to_monday_if_sunday", :name => "Christmas Day", :regions => [:us_banking]}]
      }
    end
  end


end

Holidays.merge_defs(Holidays::US_Banking.defined_regions, Holidays::US_Banking.holidays_by_month)
